version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/code
    depends_on:
      - web

  redis:
    image: "redis:7-alpine"
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  db_data:
